<?php

namespace Database\Seeders;

use App\Models\Apartment;
use App\Models\Feature;
use App\Models\GalleryItem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ApartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $images = [
            'catalog-1.jpg',
            'catalog-2.jpg',
            'gallery-1.png',
            'gallery-2.png',
            'gallery-3.png',
        ];

        foreach ($images as $image) {
            copy(resource_path('frontend/src/assets/img/catalog/' . $image), public_path('storage/' . $image));
        }

        $items = [
            [
                'title' => 'Квартира 1',
                'type' => 'apartment',
                'sold' => 0,
                'planing_type' => 'студія',
                'features' => json_encode('credit'),
                'parking_count' => 2,
                'area' => 120,
                'living_area' => 100,
                'rooms' => 3,
                'building' => 1,
                'section' => 1,
                'floor' => 3,
                'price' => 355000,
                'price_for_meter' => 1200,
                'plan' => '/catalog-1.jpg',
                'floor_plan' => '/gallery-1.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Квартира 2',
                'type' => 'apartment',
                'sold' => 0,
                'planing_type' => 'студія',
                'features' => json_encode(['installment', 'credit']),
                'parking_count' => 0,
                'area' => 84,
                'living_area' => 75,
                'rooms' => 2,
                'building' => 2,
                'section' => 1,
                'floor' => 2,
                'price' => 35000,
                'price_for_meter' => 400,
                'plan' => '/catalog-1.jpg',
                'floor_plan' => '/gallery-1.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Квартира 3',
                'type' => 'apartment',
                'sold' => 0,
                'planing_type' => 'студія',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 95,
                'living_area' => 80,
                'rooms' => 1,
                'building' => 1,
                'section' => 1,
                'floor' => 5,
                'price' => 45000,
                'price_for_meter' => 750,
                'plan' => '/catalog-1.jpg',
                'floor_plan' => '/gallery-1.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Квартира 4',
                'type' => 'apartment',
                'sold' => 0,
                'planing_type' => 'студія',
                'features' => json_encode(['credit']),
                'parking_count' => 0,
                'area' => 93,
                'living_area' => 78,
                'rooms' => 1,
                'building' => 2,
                'section' => 2,
                'floor' => 1,
                'price' => 399000,
                'price_for_meter' => 900,
                'plan' => '/catalog-1.jpg',
                'floor_plan' => '/gallery-1.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Квартира 5',
                'type' => 'apartment',
                'sold' => 0,
                'planing_type' => 'студія',
                'features' => json_encode([]),
                'parking_count' => 1,
                'area' => 140,
                'living_area' => 120,
                'rooms' => 2,
                'building' => 2,
                'section' => 2,
                'floor' => 4,
                'price' => 500000,
                'price_for_meter' => 900,
                'plan' => '/catalog-1.jpg',
                'floor_plan' => '/gallery-1.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Квартира 6',
                'type' => 'apartment',
                'sold' => 0,
                'planing_type' => 'студія',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 90,
                'living_area' => 70,
                'rooms' => 2,
                'building' => 2,
                'section' => 1,
                'floor' => 4,
                'price' => 400000,
                'price_for_meter' => 900,
                'plan' => '/catalog-1.jpg',
                'floor_plan' => '/gallery-1.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Квартира 7',
                'type' => 'apartment',
                'sold' => 0,
                'planing_type' => 'студія',
                'features' => json_encode([]),
                'parking_count' => 0,
                'area' => 90,
                'living_area' => 75,
                'rooms' => 2,
                'building' => 2,
                'section' => 2,
                'floor' => 2,
                'price' => 455000,
                'price_for_meter' => 1000,
                'plan' => '/catalog-1.jpg',
                'floor_plan' => '/gallery-1.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Паркінг 1',
                'type' => 'parking',
                'sold' => 0,
                'planing_type' => 'паркінг',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 10,
                'living_area' => 0,
                'rooms' => 0,
                'building' => 1,
                'section' => 1,
                'floor' => 0,
                'price' => 5000,
                'price_for_meter' => 500,
                'plan' => '/catalog-2.jpg',
                'floor_plan' => '/gallery-3.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Паркінг 1',
                'type' => 'parking',
                'sold' => 0,
                'planing_type' => 'паркінг',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 10,
                'living_area' => 0,
                'rooms' => 0,
                'building' => 1,
                'section' => 1,
                'floor' => 0,
                'price' => 5000,
                'price_for_meter' => 500,
                'plan' => '/catalog-2.jpg',
                'floor_plan' => '/gallery-3.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Паркінг 2',
                'type' => 'parking',
                'sold' => 0,
                'planing_type' => 'паркінг',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 10,
                'living_area' => 0,
                'rooms' => 0,
                'building' => 2,
                'section' => 2,
                'floor' => 0,
                'price' => 7000,
                'price_for_meter' => 500,
                'plan' => '/catalog-2.jpg',
                'floor_plan' => '/gallery-3.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Паркінг 3',
                'type' => 'parking',
                'sold' => 0,
                'planing_type' => 'паркінг',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 10,
                'living_area' => 0,
                'rooms' => 0,
                'building' => 1,
                'section' => 2,
                'floor' => 0,
                'price' => 5500,
                'price_for_meter' => 500,
                'plan' => '/catalog-2.jpg',
                'floor_plan' => '/gallery-3.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Паркінг 3',
                'type' => 'parking',
                'sold' => 0,
                'planing_type' => 'паркінг',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 10,
                'living_area' => 0,
                'rooms' => 0,
                'building' => 2,
                'section' => 3,
                'floor' => 0,
                'price' => 6000,
                'price_for_meter' => 500,
                'plan' => '/catalog-2.jpg',
                'floor_plan' => '/gallery-3.png',
                'gen_plan' => '/gallery-2.png',
            ],
            [
                'title' => 'Паркінг 4',
                'type' => 'parking',
                'sold' => 0,
                'planing_type' => 'паркінг',
                'features' => json_encode(['credit']),
                'parking_count' => 1,
                'area' => 10,
                'living_area' => 0,
                'rooms' => 0,
                'building' => 3,
                'section' => 3,
                'floor' => 0,
                'price' => 8000,
                'price_for_meter' => 500,
                'plan' => '/catalog-2.jpg',
                'floor_plan' => '/gallery-3.png',
                'gen_plan' => '/gallery-2.png',
            ],

        ];

        Apartment::query()->delete();

        foreach ($items as $item) {
            Apartment::create($item);
        }
    }
}
